name: hello-gtk-frame # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Mono GTK example on ubuntu-frame # 79 char long summary
description: |
  Mono GTK ui example that works on ubuntu-frame by leveraging Ubuntu Core

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


apps:
  mono-gui-snap:
    command-chain:
      - env-setup
      - usr/local/bin/x11_kiosk_launch
    command:  usr/bin/mono $SNAP/usr/lib/hello/hello-world.exe
    daemon: simple
    restart-condition: always
    plugs:
      - opengl
      - wayland
      - network-bind


parts:
  hello-gtk-frame:
    # See 'snapcraft plugins'
    plugin: make
    source: .
    stage-packages:
      - mono-runtime
      - libmono-system4.0-cil
      - mesa-utils
    build-packages:
      - build-essential
      - pkg-config
      - cli-common-dev
      - mono-devel
      - gtk-sharp2
    stage-snaps: [mir-kiosk-x11]


layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/lib/cli:
    bind: $SNAP/usr/lib/cli